apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  # <resource_name(s)>.<group_name>
  name: virtualmachines.cloudnative.group.group
spec:
  group: cloudnative.group.group
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          description: VirtualMachine is the Schema for the virtualmachines API
          properties:
            apiVersion:
              description: 'APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/apis-conventions.md#resources'
              type: string
            kind:
              description: 'Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/apis-conventions.md#types-kinds'
              type: string
            metadata:
              type: object
            spec:
              description: VirtualMachineSpec defines the desired state of VirtualMachine
              properties:
                name:
                  description: Name is the name of the virtual machine
                  type: string
                cpu:
                  description: CPU is the number of CPUs for the virtual machine
                  type: integer
                memory:
                  description: Memory is the amount of memory for the virtual machine
                  type: string
                image:
                  description: Image is the name of the image used for the virtual machine
                  type: string
              required:
                - name
                - cpu
                - memory
                - image
              type: object
  names:
    kind: VirtualMachine
    singular: virtualmachine
    plural: virtualmachines
    shortNames:
      - vm
  scope: Namespaced